// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $api_tickets from "./routes/api/tickets.ts";
import * as $api_tickets_id_ from "./routes/api/tickets/[id].ts";
import * as $index from "./routes/index.tsx";
import * as $TicketList from "./islands/TicketList.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/api/tickets.ts": $api_tickets,
    "./routes/api/tickets/[id].ts": $api_tickets_id_,
    "./routes/index.tsx": $index,
  },
  islands: {
    "./islands/TicketList.tsx": $TicketList,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
